### ISSUE TITLE
An example 3.0 USX Bible for testing

### ISSUE THREAD

**Issue by jonbitgood** [ubsicap/usx#40]
I'd like to write a xslt for usx (#39) but most of the examples on the DBL seem to be 2.7. Is it possible to get a complete sample Bible that has all the features of 3.0 for testing and validating scripts that will work with usx 3.0?

**Comment by klassenjm** [comment]
Hi @jonBitgood. Nearly all text content is the DBL has been submitted via Paratext. Paratext 9 is the first version which will support USFM 3, and generate USX 3 XML. It is still in available in beta at this point, but no uploads to DBL from Paratext 9 in USX 3 have occurred yet. That will not happen for some weeks yet, and not likely until Paratext 9 is at a release version, and until some more communication has happened with partners.

Sorry, but hope the background helps.
