### ISSUE TITLE
License for USX?

### ISSUE THREAD

**Issue by putihhijau** [ubsicap/usx#44]
Hello everyone,

First off - thank you very much for the efforts for this.

I'm wondering what, if any, license governs USX?

(https://ubsicap.github.io/usx/ includes a copyright notice, hence my question).

Best Regards
Thomas

**Comment by klassenjm** [comment]
Hello Thomas,

I'm sorry there has been a delay in responding to your question.

No thought has been given to a license for governing USX. That's probably an oversight we should correct. You're correct that a copyright notice exist on the written documentation.

Your question is actually the first of its kind. Would you be able to describe your specific interest? Are you wishing to republish and share the documentation in another form, or are you wishing to extend USX in some way? Your reply will help us consider what type of license is needed.

Jeff

**Comment by putihhijau** [comment]
Hello,

No worries and thanks again.

My specific interest that brought me here is that, I was considering building some software to aid members of the danish "folkekirke" (national church or people's church of DK). 

To be very specific: Each Sunday or other sacred day in the year has some attributes in our belief among which is

- A set excerpts from Old and New Testament. On coming Friday we'll be using Matthew 7, 7-14, Psalm 130 and Letter to the Hebrews 10, 19-25.

What passages to use is defined and fixed "forever" in a rotating manner. So I was thinking to use some of your basic entities etc to map the sunday (or sacred day) to passages of the books. I _could_ invent my own definitions of references etc but why if I can use something nice that already exists.

It's not a professional project at all. 

Hope this clarifies a bit.

Thomas

**Comment by jonbitgood** [comment]
Hey putihhijau,

Depending on where you are, your copyright laws may not formally recognize data schema copyrights. Indeed, two major players, US and UK do not formally recognize copyrights of data schemas. see _precSAS Institute Inc. v World Programming Ltd_ for the UK and _Edison v. Lubin_ for the US. 

That's pretty much all moot though as UBS is a great organization focused on helping the dissemination of the Bible to the world and since USX is a decedent of / influenced by several other systems OSIS, USFX and Zefania.

_Some interesting reading from the [Journal of Intellectual Property Law.](https://digitalcommons.law.uga.edu/cgi/viewcontent.cgi?article=1360&context=jipl) and the [WMLS](https://scholarship.law.wm.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=1043&context=facpubs)_

**Comment by klassenjm** [comment]
Thanks for adding these notes, Jon.

Thomas - although I have not really clarified anything by pointing at a license, there should be no concern on your end with using the USX schema and entities to mark up your content. This repo is here as documentation of something which is used widely internally among Bible Societies and other Bible agencies for storing Bible data. If it is of help in accomplishing your goals, that's excellent.

Jeff

**Comment by davidbaines** [comment]
Is there anything to be gained, or lost, by explicitly offering the USX schema under a Creative Commons licence? The aim of a licence is to make it clear what is allowed use and what isn't. 

All the data in the repository can be copied and then modified by others according to the Github License:

Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.
