### ISSUE TITLE
Just a Question Regarding JSON support

### ISSUE THREAD

**Issue by alilland** [ubsicap/usx#56]
I just got my DBL LCH approval, so i'm hunting through documentation to get myself familiar with the XML. Just curious has anyone written any helpers for porting schema over to JSON?

also, the link to this github repo is broken on the help page, here is the page that used to link to this repo - https://app.thedigitalbiblelibrary.org/static/docs/usx/schema.html

**Comment by klassenjm** [comment]
I would suggest taking a look at the following:
https://github.com/mvh-solutions/nice-usfm-json
