### ISSUE TITLE
Give etymology for <char>

### ISSUE THREAD

**Issue by merchako** [ubsicap/usx#57]
**Problem**: My co-worker and I were very confused as to why `<char>` would represent a string of characters! I believe most developers would be. 

**Solution**: Give a longer description of what a `<char>` is, and include etymology.

In most of programming, a "char" is character, such as a value holding one byte in C (one ASCII `char`) or a unicode character. It took us a long to figure out that's not what USX `<char>` is. 

As a designer, I have experience with layout programs in which every style is either a "Character Style" or a "Paragraph Style". Perhaps that's the reason why the keyword "char" was chosen—because it's a Character Style? 

—

FWIW, if my etymology guess is right, I'd suggest doing the same for `<para>`. These days HTML semantics really dominates the mental space, especially now that Paratext 10 is being developed with web technologies. 

In HTML, a paragraph `<p>` is specifically *not* a heading `<h1–6>`, but in USX, a heading `h` is a type of Paragraph Style. Could you help us out as we read the documentation by mentioning these kinds of differences? Even including phrases like "Paragraph Style" could help attach the mental model to the layout world instead of the many competing mental spaces developers are in.

**Comment by klassenjm** [comment]
Hi Alex,

Before making specific comments, let me point you to the main location(s) where USFM/USX/USJ (collectively USFM) are being maintained and developed. (these earlier repos will need to be archived at some point once USFM 3.1 is fully 'released')

- If you go to http://usfm.bible you'll find the main repos tracking development. In that space, the [tcdocs](https://github.com/usfm-bible/tcdocs) repo is the main place for the "technical committee" documents.

- See https://docs.usfm.bible for the latest documentation for USFM 3.1
- Check out https://docs.usfm.bible/usfm/3.1/release-notes.html for the information on USFM 3.1

You'll see that an effort has been made to move USFM towards being a single data model which can be expressed / serialized in 3 formats (USFM - as backslash based USFM , USX - XML, USJ - JSON). There are tools available to validate data and round-trip between these formats.

The elements used in USX (specifically `<para>` and `<char>`) have been in use in this format for many years now -- and will not likely change. You're right that the para and char etymology related to paragraph and character styles/types. The `style` attribute for each is what specifies the type (and is the close association with USFM - which has been with us for much longer).

`h` is text for a running header, and not so much a heading. That `'h` key started in USFM a long time before HTML.

I suppose I'm attempting to highlight that USFM/USX are not easily moved towards a complete reworking of tag names. USJ is the newest option. Perhaps what you're pointing moreso is the need for more clarity in the documentation. Perhaps evaluate the current documentation site and leave some comments in the tcdocs [Issues](https://github.com/usfm-bible/tcdocs/issues) area if there is confusion.

**Comment by jonbitgood** [comment]
@merchako It's an umbrella tag that comes from the Character Marking USFM that handled [character style](https://ubsicap.github.io/usfm/characters/index.html). CharMark or CharStyle would have been awkward and it just got truncated. But as old Martin Fowler said: *"There are only two hard things in Computer Science: cache invalidation and naming things"*

@klassenjm It's great to see the 3.1 docs update! I'm looking forward to seeing the upcoming example **USJ** Bibles. Will they also be uploaded to [examples.bsb](https://github.com/usfm-bible/examples.bsb)?

**Comment by klassenjm** [comment]
[example.bsb](https://github.com/usfm-bible/examples.bsb) is a very new initiative, so please note that right now that text is not USFM 3.1 compliant. The initial effort will be to work through the text and make it a solid exemplar, and I imagine also then to provide the corresponding USX and USJ formats. The tools in [/python/scripts](https://github.com/usfm-bible/tcdocs/tree/main/python/scripts) also provide for converting between the formats (I believe an .exe for the converter will be included with a 3.1 release).

**Comment by merchako** [comment]
Thank you for the pointers. Yes, naming things is very hard! I'm reminded of the animals God brought before Adam in Genesis 2:19. I deeply respect the pioneering work of those who've come before me to create a standard older than HTML. Even if you wanted to rename the tags, it wouldn't be a task to be taken lightly.

So you're right, I'm more interested in adding clarity and context to the documentation than in changing the standard.
